AppRazor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
namespace AppRazor.Pages
{
	public class IndexModel : PageModel
    {
        readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }
    }
}

AppRazor/Pages/ListOfGroups.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Models.Interfaces;
using Services;

namespace AppRazor.Pages
{
    public class ListOfGroupsModel : PageModel
    {
        readonly IMusicGroupsService _service = null;
        readonly ILogger<ListOfGroupsModel> _logger = null;

        [BindProperty]
        public bool UseSeeds { get; set; } = true;
        
        public List<IMusicGroup> MusicGroups { get; set; }

        public int NrOfGroups { get; set; }

        //Pagination
        public int NrOfPages { get; set; }
        public int PageSize { get; } = 10;

        public int ThisPageNr { get; set; } = 0;
        public int PrevPageNr { get; set; } = 0;
        public int NextPageNr { get; set; } = 0;
        public int NrVisiblePages { get; set; } = 0;

        //ModelBinding for the form
        [BindProperty]
        public string SearchFilter { get; set; } = null;

        //will execute on a Get request
        public async Task<IActionResult> OnGet()
        {   
            //Read a QueryParameters
            if (int.TryParse(Request.Query["pagenr"], out int pagenr))
            {
                ThisPageNr = pagenr;
            }

            SearchFilter = Request.Query["search"];

            //Use the Service
            var resp = await _service.ReadMusicGroupsAsync(UseSeeds, false, SearchFilter, ThisPageNr, PageSize);
            MusicGroups = resp.PageItems;
            NrOfGroups = resp.DbItemsCount;

            //Pagination
            UpdatePagination(resp.DbItemsCount);

            return Page();
        }

        private void UpdatePagination(int nrOfItems)
        {
            //Pagination
            NrOfPages = (int)Math.Ceiling((double)nrOfItems / PageSize);
            PrevPageNr = Math.Max(0, ThisPageNr - 1);
            NextPageNr = Math.Min(NrOfPages - 1, ThisPageNr + 1);
            NrVisiblePages = Math.Min(10, NrOfPages);
        }

        public async Task<IActionResult> OnPostSearch()
        {
            //Use the Service
            var resp = await _service.ReadMusicGroupsAsync(UseSeeds, false, SearchFilter, ThisPageNr, PageSize);
            MusicGroups = resp.PageItems;
            NrOfGroups = resp.DbItemsCount;

            //Pagination
            UpdatePagination(resp.DbItemsCount);

            //Page is rendered as the postback is part of the form tag
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteGroup(Guid groupId)
        {
            await _service.DeleteMusicGroupAsync(groupId);

            //Use the Service
            var resp = await _service.ReadMusicGroupsAsync(UseSeeds, false, SearchFilter, ThisPageNr, PageSize);
            MusicGroups = resp.PageItems;
            NrOfGroups = resp.DbItemsCount;

            //Pagination
            UpdatePagination(resp.DbItemsCount);

            return Page();
        }

        //Inject services just like in WebApi
        public ListOfGroupsModel(IMusicGroupsService service, ILogger<ListOfGroupsModel> logger)
        {
            _service = service;
            _logger = logger;
        }
    }
}

AppRazor/Pages/ViewGroup.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Models.Interfaces;
using Services;

namespace AppRazor.Pages
{
	public class ViewGroupModel : PageModel
    {
        //Just like for WebApi
        readonly IMusicGroupsService _service = null;
        readonly ILogger<ViewGroupModel> _logger = null;

        public IMusicGroup MusicGroup  { get; set; }

        public async Task<IActionResult> OnGet()
        {
            Guid _groupId = Guid.Parse(Request.Query["id"]);
            MusicGroup = (await _service.ReadMusicGroupAsync(_groupId, false)).Item;

            return Page();
        }

        //Inject services just like in WebApi
        public ViewGroupModel(IMusicGroupsService service, ILogger<ViewGroupModel> logger)
        {
            _service = service;
            _logger = logger;
        }
    }
}

AppRazor/Pages/Index.cshtml
@page
@model AppRazor.Pages.IndexModel
@{
    ViewData["Title"] = "Home";
}
<!-- Individual pages, I place them with <main> tag. Will become separate Razor Pages -->
<!-- Page Welcome -->
<div class="container px-4 py-4" id="home">
    <div class="bg-body-tertiary p-5 rounded">
        <div class="col-sm-8 py-5 mx-auto">
            <h1 class="display-5 fw-normal">Welcome to My project A</h1>
            <h3>By: Cecilia Forsberg Andersson</h3>
            <p class="fs-5">
                This example is part of the ASP.NET Web Development course, and shows how to combine ASP.NET Razorpages and MVC.
                Pages are rendered in ASP.NET backend using C# and Razor syntax. Frontend is using css, javascript, Bootstrap and JQuery.
                Backend architecture is MVC and MVVM.
            </p>
            <p>
                We use loosely coupled software layers so we use communicate with a SQL Database either through EntityFramework Core integrated in the application or via a WebApi.
                All without any code changes in the Application except in the Dependency Injection where we simply inject different services.
            </p>
            <p>
                <a class="btn btn-primary" href="https://webapi-public-72962524.azurewebsites.net/swagger" role="button">External public webapi datasource</a>
            </p>
            <p>Enjoy!</p>
        </div>
    </div>
</div>

AppRazor/Pages/ListOfGroups.cshtml
@page
@model AppRazor.Pages.ListOfGroupsModel
@{
    ViewData["Title"] = "List groups";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@attribute [IgnoreAntiforgeryToken]
<!-- Page List of groups -->
<div class="container px-4 py-4" id="list-of-groups">
    <h2 class="pb-2 border-bottom">List of Music bands</h2>

    <p>Below are some of the worlds most famous Music bands.</p>
    <p>The database contains @Model.NrOfGroups music groups with the search criteria</p>

    <form method="post" class="needs-validation" method="post" novalidate>
        <label class="form-check-label" for="useSeeds">Use seeded data</label>
        <input asp-for="UseSeeds" class="form-check-input" type="checkbox" id="useSeeds">
        <div class="row row-cols-1 row-cols-lg-4 align-items-stretch g-4 py-5">
            <div class="col-md-7 col-lg-10">
                <div class="row mb-2 text-center">
                    <!-- Search filter-->
                    <div class="row mb-2 text-center">
                        <div class="col-md-6 ">
                            <input asp-for="SearchFilter" class="form-control" type="search" placeholder="Search" aria-label="Search">
                        </div>
                        <div class="col-md-2 ">
                            <button asp-page-handler="Search" class="btn btn-outline-success" type="submit">Search</button>
                        </div>
                    </div>
                </div>
                <div class="row mb-2 text-center">
                    <!-- This is where selected item id will be stored -->
                    <input type="hidden" name="groupId" data-seido-selected-item-id-target />

                    <div class="col-md-10 themed-grid-head-col">Group Name</div>
                    <div class="col-md-2 themed-grid-head-col">
                        <a href="~/Members/EditGroup" class="btn btn-success btn-sm m-1" type="button">New</a>
                    </div>
                </div>

                <div class="row mb-2 text-center">

                        @if (Model.MusicGroups is not null)
                        {
                            @foreach (var item in Model.MusicGroups)
                            {
                                <div class="col-md-10 themed-grid-col">
                                    <a href="~/ViewGroup?id=@item.MusicGroupId">
                                        @item.Name
                                    </a>
                                </div>
                                    <div class="col-md-2 themed-grid-col">
                                        <a href="~/Members/EditGroup?id=@item.MusicGroupId" class="btn btn-secondary btn-sm m-1" type="button">Edit</a>

                                        <!-- Button to trigger modal confirmation with modal in the form tag -->
                                        <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#delModal"
                                                data-seido-modal-body="@item.Name is about to be deleted."
                                                data-seido-selected-item-id="@item.MusicGroupId">
                                            Del
                                        </button>
                                    </div>
                            }
                            <nav aria-label="Standard pagination example">
                                <ul class="pagination">
                                    <li class="page-item">
                                        <a class="page-link" href="~/ListOfGroups?pagenr=@Model.PrevPageNr&search=@Model.SearchFilter" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    </li>
                                    @for (int i = 0; i < Model.NrVisiblePages; i++)
                                    {
                                        <li class="page-item">
                                            <a class="page-link" href="~/ListOfGroups?pagenr=@i&search=@Model.SearchFilter">@(i + 1)</a>
                                        </li>

                                    }
                                    <li class="page-item">
                                        <a class="page-link" href="~/ListOfGroups?pagenr=@Model.NextPageNr&search=@Model.SearchFilter" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        }

                        <!-- Modal in the form tag -->
                        <div class="modal fade" id="delModal" tabindex="-1" aria-labelledby="softModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title text-danger" id="softModalLabel">Confirm deletion</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        Hello from modal
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                        <button type="submit" asp-page-handler="DeleteGroup" class="btn btn-primary btn-danger">Ok</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </form>
</div>

AppRazor/Pages/ViewGroup.cshtml
@page
@model AppRazor.Pages.ViewGroupModel
@{
    ViewData["Title"] = "View group";
}

<!-- Page view-group -->
<div class="container px-4 py-4" id="view-group">
    <h2 class="pb-2 border-bottom">
    View details of a music group
        <a href="~/Members/EditGroup?id=@Model.MusicGroup.MusicGroupId">
            <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#edit" /></svg>
        </a>
    </h2>
    <form class="needs-validation" novalidate>
        <div class="row row-cols-1 row-cols-lg-4 align-items-stretch g-4 py-5">
            <div class="col-md-7 col-lg-10">

                <div class="row g-3">
                    <div class="col-sm-6">
                        <label for="groupName" class="form-label">GroupName</label>
                        <input type="text" class="form-control" id="groupName" value="@Model.MusicGroup.Name" readonly>
                    </div>

                    <div class="col-sm-6">
                        <label for="genre" class="form-label">Genre</label>
                        <input type="text" class="form-control" id="genre" value="@Model.MusicGroup.Genre" readonly>
                    </div>

                    <div class="col-sm-6">
                    </div>
                    <div class="col-sm-6">
                        <label for="established" class="form-label">Established Year</label>
                        <input type="text" class="form-control" id="established" value="@Model.MusicGroup.EstablishedYear" readonly>
                    </div>
                </div>
                <div class="row g-1">
                    <h3 class="pb-2">Artists</h3>

                    <div class="row mb-2 text-center">
                        <div class="col-md-12 themed-grid-head-col">Name</div>
                    </div>
                    @foreach (var item in Model.MusicGroup.Artists)
                    {
                        <div class="row mb-2 text-center">
                            <div class="col-md-12 themed-grid-col">@item.FirstName @item.LastName</div>
                        </div>
                    }
                </div>

                <div class="row g-1">
                    <h3 class="pb-2">Albums</h3>

                    <div class="row mb-2 text-center">
                        <div class="col-md-10 themed-grid-head-col">Name</div>
                        <div class="col-md-2 themed-grid-head-col">Release Year</div>
                    </div>
                    @foreach (var item in Model.MusicGroup.Albums)
                    {
                        <div class="row mb-2 text-center">
                            <div class="col-md-10 themed-grid-col">@item.Name</div>
                            <div class="col-md-2 themed-grid-col">@item.ReleaseYear</div>
                        </div>
                    }
                </div>

            </div>
        </div>
    </form>
</div>